import com.magenic.models.Base;
import com.magenic.models.Extra;
import com.magenic.utils.Calculations;


dialect "java"
rule "Calc Rule"

    when
        extra : Extra (calcType == "Standard");
        Base : Base ();
    then
        Calculations calculations = new Calculations();

        base.setResult(calculations.doCalc(
            base.getPrice(),
            base.getPercent(),
            extra.getBaseValue());
end